#!/usr/bin/env python
# -*- coding: utf-8 -*-

def fib(n):
    a, b = 0, 1
    while b < n:
        print b,
        a, b = b, a+b

def fibonan(n):
    result = []
    a, b = 0, 1
    while b < n:
        result.append(b)
        a, b = b, a+b
    return result

#fibonan(10)
#fib(10)
